### ISSUE TITLE
No License??

### ISSUE THREAD

**Issue by DestroyerXyz** [bitwarden/brand#11]
Don't you want to have a GNU Documentation License or something with this??

**Comment by Pablohn26** [comment]
Another option would be this one

[Brand](https://github.com/bitwarden/brand) by [Bitwarden Inc](https://bitwarden.com/about/) is licensed under CC BY-NC-ND 4.0 CC

![IMG492](https://user-images.githubusercontent.com/1228418/98238131-3ae2cf00-1f66-11eb-9a88-37e3b6031b73.png)

**Comment by DestroyerXyz** [comment]
Yes, but this is just a copyright mark. You have to put the CC BY-NC-ND 4.0 LICENSE file in the repo.

**Comment by Pablohn26** [comment]
I have added [my proposal](https://github.com/bitwarden/brand/pull/14) :)

**Comment by DestroyerXyz** [comment]
I think the license actually starts from line 57

**Comment by DestroyerXyz** [comment]
You have to also put this in ever file in brand:
```
Copyright 2020 Bitwarden Inc.
Licensed under AGPL-3.0-or-later
```
