### ISSUE TITLE
the logo on the bitwarden.com website is hard to see in dark theme

### ISSUE THREAD

**Issue by jetersen** [bitwarden/brand#17]
On Edge chromium it is hard to see the hard icon on the vertical bar in dark theme.
I believe web browsers support loading icon based on theme.

https://blog.tomayac.com/2019/09/21/prefers-color-scheme-in-svg-favicons-for-dark-mode-icons/

![image](https://user-images.githubusercontent.com/1661688/110368122-e2712a80-8048-11eb-8bc4-dcc647c69ce6.png)

**Comment by jidanni** [comment]
Indeed. Here we compare https://community.bitwarden.com/ and https://bitwarden.com/ 
![20240406T164037](https://github.com/bitwarden/brand/assets/1230959/fcbc91d8-4fd9-4b5e-a672-77427af430fa)

**Comment by jidanni** [comment]
https://github.com/bitwarden/brand

![20240406T164607](https://github.com/bitwarden/brand/assets/1230959/c77c4555-19dc-4b8d-b559-900b434f2c3d)

**Comment by jidanni** [comment]
https://github.com/orgs/community/discussions/116831

**Comment by DanHillesheim** [comment]
Thank you for your contributions! Many of these issues have been or will be address in the coming weeks.
