### ISSUE TITLE
Bitwarden's Microsoft Store Logo Different From That of Downloaded from Website

### ISSUE THREAD

**Issue by ghost** [bitwarden/brand#21]
Here's what the Bitwarden's logo looks like when it's installed from Microsoft Store
👇
![Screenshot (3)](https://user-images.githubusercontent.com/80682093/129475571-c5d92ad4-ab0c-4345-9ab9-d8761fb058b7.png)

It's entirely different from the one download from Bitwarden's website.

**Comment by Ghoul149** [comment]
@Nihal247 The Bitwarden's logo you have mentioned is same as the official Bitwarden's Logo
